/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChallengePicker: typeof import('./src/components/ChallengePicker.vue')['default']
    ComponentPicker: typeof import('./src/components/ChallengePicker.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    QRCode: typeof import('./src/components/QRCode.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
